(defun fix-feedparser-python ()
  "Get readable formatting for a serialized feedparser datastructure"
  (interactive)
  (save-excursion
    (goto-char (point-min))
    (replace-string "{'" "{\n'")
    (goto-char (point-min))
    (replace-string "{u" "{\nu")
    (goto-char (point-min))
    (replace-string ", '" ",\n'")
    (goto-char (point-min))
    (replace-string ", u" ",\nu")
    (goto-char (point-min))
    (replace-string "[{" "[\n{")
    (goto-char (point-min))
    (replace-string "}]" "}\n]")
    (goto-char (point-min))
    (replace-string ", {" ",\n{")
    (goto-char (point-min))
    (replace-string "'}" "'\n}")
    (goto-char (point-min))
    (replace-string "]}" "]\n}")
    (goto-char (point-min))
    (replace-string "}}" "}\n}")
    (goto-char (point-min))
    (indent-region (point-min) (point-max))))
